version: '3.9'

networks:
  innerImage:

services:
  php-apache-environment:
    container_name: srv_apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./app:/var/www/hamsterauto/
      - ./app/var/log:/var/log/apache2/
      #- ./conf/SSL/aflautocert.crt:/etc/ssl/certs/aflautocert.crt
      #- ./conf/SSL/aflautocert.key:/etc/ssl/private/aflautocert.key
    ports:
      - "8001:80"
      #- "8443:443"
    environment:
      TZ: Europe/Paris
    networks:
      - innerImage

  database:
    container_name: database_mysql
    image: mysql
    restart: always
    volumes:
      - ./app/migrations/hamsterauto_dump_SQL.sql:/docker-entrypoint-initdb.d/hamsterauto_dump_SQL.sql
      - ./app/migrations/create-user.sql:/docker-entrypoint-initdb.d/create-user.sql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: Europe/Paris
    ports:
      - "9906:3306"
    networks:
      - innerImage

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: database
      TZ: Europe/Paris
    depends_on:
      - database
    networks:
      - innerImage
