version: '3.9'

services:
  hamsterauto:
    container_name: hamsterauto_app
    image: 057133510824.dkr.ecr.eu-west-3.amazonaws.com/hamsterauto:latest
    volumes:
        - type: volume
          source: app
          target: /opt/hamsterauto
    depends_on:
      - database
    networks:
      - hamsterauto
  database:
    container_name: hamsterauto_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: Europe/Paris
    ports:
      - "9906:3306"
    networks:
      - hamsterauto
  phpmyadmin:
    container_name: hamsterauto_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: database
      TZ: Europe/Paris
    depends_on:
      - database
    networks:
      - hamsterauto

volumes:
    app:
      name: hamsterauto_app