version: '3.9'

networks:
  innerImage:

services:
  php-apache-environment:
    container_name: srv_apache
    build:
      context: .
      dockerfile: Dockerfile_dev
    depends_on:
      - database
    volumes:
      - ./app:/var/www/hamsterauto/
      - ./app/var/log:/var/log/apache2/
    ports:
      - "8001:80"
    environment:
      TZ: Europe/Paris
    networks:
      - innerImage

  database:
    container_name: database_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: Europe/Paris
    ports:
      - "9906:3306"
    networks:
      - innerImage

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: database
      TZ: Europe/Paris
    depends_on:
      - database
    networks:
      - innerImage