version: '3.9'

services:
  hamsterauto:
    #image: 057133510824.dkr.ecr.eu-west-3.amazonaws.com/hamsterauto:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - type: bind
          source: /var/test/hamsterauto/
          target: /opt/hamsterauto/